In [113]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [114]:
df = pd.read_csv("/home/root1/Downloads/Social_Network_Ads.csv")

In [115]:
label = {'Male': 0 ,"Female" : 1}
df['Gender'].replace(label, inplace= True)
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       0   19            19000          0
1    15810944       0   35            20000          0
2    15668575       1   26            43000          0
3    15603246       1   27            57000          0
4    15804002       0   19            76000          0
5    15728773       0   27            58000          0
6    15598044       1   27            84000          0
7    15694829       1   32           150000          1
8    15600575       0   25            33000          0
9    15727311       1   35            65000          0
10   15570769       1   26            80000          0
11   15606274       1   26            52000          0
12   15746139       0   20            86000          0
13   15704987       0   32            18000          0
14   15628972       0   18            82000          0
15   15697686       0   29            80000          0
16   15733883       0   47            25000          1
17   15617482       0   45            26000          1
18   15704583       0   46            28000          1
19   15621083       1   48            29000          1
20   15649487       0   45            22000          1
21   15736760       1   47            49000          1
22   15714658       0   48            41000          1
23   15599081       1   45            22000          1
24   15705113       0   46            23000          1
25   15631159       0   47            20000          1
26   15792818       0   49            28000          1
27   15633531       1   47            30000          1
28   15744529       0   29            43000          0
29   15669656       0   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430       1   60            46000          1
371  15774744       0   60            83000          1
372  15629885       1   39            73000          0
373  15708791       0   59           130000          1
374  15793890       1   37            80000          0
375  15646091       1   46            32000          1
376  15596984       1   46            74000          0
377  15800215       1   42            53000          0
378  15577806       0   41            87000          1
379  15749381       1   58            23000          1
380  15683758       0   42            64000          0
381  15670615       0   48            33000          1
382  15715622       1   44           139000          1
383  15707634       0   49            28000          1
384  15806901       1   57            33000          1
385  15775335       0   56            60000          1
386  15724150       1   49            39000          1
387  15627220       0   39            71000          0
388  15672330       0   47            34000          1
389  15668521       1   48            35000          1
390  15807837       0   48            33000          1
391  15592570       0   47            23000          1
392  15748589       1   45            45000          1
393  15635893       0   60            42000          1
394  15757632       1   39            59000          0
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

[400 rows x 5 columns]

In [116]:
y = df.iloc[:,-1]

In [117]:
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      1
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     0
29     0
      ..
370    1
371    1
372    0
373    1
374    0
375    1
376    0
377    0
378    1
379    1
380    0
381    1
382    1
383    1
384    1
385    1
386    1
387    0
388    1
389    1
390    1
391    1
392    1
393    1
394    0
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [118]:
X = df.iloc[:,1:4]
scaler = StandardScaler()
print(scaler.fit(X))
print(scaler.mean_)
X=scaler.transform(X)


StandardScaler()
[5.10000e-01 3.76550e+01 6.97425e+04]


In [119]:
X = pd.DataFrame(X)
X

0         1         2
0   -1.020204 -1.781797 -1.490046
1   -1.020204 -0.253587 -1.460681
2    0.980196 -1.113206 -0.785290
3    0.980196 -1.017692 -0.374182
4   -1.020204 -1.781797  0.183751
5   -1.020204 -1.017692 -0.344817
6    0.980196 -1.017692  0.418669
7    0.980196 -0.540127  2.356750
8   -1.020204 -1.208719 -1.078938
9    0.980196 -0.253587 -0.139263
10   0.980196 -1.113206  0.301210
11   0.980196 -1.113206 -0.521006
12  -1.020204 -1.686284  0.477399
13  -1.020204 -0.540127 -1.519411
14  -1.020204 -1.877311  0.359940
15  -1.020204 -0.826666  0.301210
16  -1.020204  0.892570 -1.313857
17  -1.020204  0.701544 -1.284492
18  -1.020204  0.797057 -1.225763
19   0.980196  0.988083 -1.196398
20  -1.020204  0.701544 -1.401952
21   0.980196  0.892570 -0.609101
22  -1.020204  0.988083 -0.844019
23   0.980196  0.701544 -1.401952
24  -1.020204  0.797057 -1.372587
25  -1.020204  0.892570 -1.460681
26  -1.020204  1.083596 -1.225763
27   0.980196  0.892570 -1.167033
28  -1.020204 -0.826666 -0.785290
29  -1.020204 -0.635640 -1.519411
..        ...       ...       ...
370  0.980196  2.134241 -0.697195
371 -1.020204  2.134241  0.389305
372  0.980196  0.128465  0.095656
373 -1.020204  2.038728  1.769453
374  0.980196 -0.062561  0.301210
375  0.980196  0.797057 -1.108303
376  0.980196  0.797057  0.125021
377  0.980196  0.415005 -0.491641
378 -1.020204  0.319491  0.506764
379  0.980196  1.943215 -1.372587
380 -1.020204  0.415005 -0.168628
381 -1.020204  0.988083 -1.078938
382  0.980196  0.606031  2.033737
383 -1.020204  1.083596 -1.225763
384  0.980196  1.847701 -1.078938
385 -1.020204  1.752188 -0.286087
386  0.980196  1.083596 -0.902749
387 -1.020204  0.128465  0.036926
388 -1.020204  0.892570 -1.049573
389  0.980196  0.988083 -1.020209
390 -1.020204  0.988083 -1.078938
391 -1.020204  0.892570 -1.372587
392  0.980196  0.701544 -0.726560
393 -1.020204  2.134241 -0.814655
394  0.980196  0.128465 -0.315452
395  0.980196  0.797057 -0.844019
396 -1.020204  1.274623 -1.372587
397  0.980196  1.179110 -1.460681
398 -1.020204 -0.158074 -1.078938
399  0.980196  1.083596 -0.990844

[400 rows x 3 columns]

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [121]:
X_train

0         1         2
3    0.980196 -1.017692 -0.374182
18  -1.020204  0.797057 -1.225763
202  0.980196  0.128465  1.886912
250  0.980196  0.606031 -0.902749
274  0.980196  1.847701 -1.284492
63  -1.020204 -0.540127  1.475804
248 -1.020204  0.319491 -0.521006
301 -1.020204  0.988083  0.125021
108 -1.020204 -1.113206  0.477399
90  -1.020204 -1.495258  0.330575
233 -1.020204  1.083596  0.477399
335  0.980196 -0.158074 -0.462276
118 -1.020204  0.223978 -0.315452
220  0.980196  0.319491  0.301210
180 -1.020204 -1.113206 -1.578141
314  0.980196  0.128465  0.271845
373 -1.020204  2.038728  1.769453
380 -1.020204  0.415005 -0.168628
239  0.980196  1.465649  2.151196
75  -1.020204 -0.349100  1.240885
247  0.980196  1.847701  1.534534
110  0.980196  0.128465  0.036926
16  -1.020204  0.892570 -1.313857
66  -1.020204 -1.304232 -1.490046
153  0.980196 -0.158074 -0.579736
7    0.980196 -0.540127  2.356750
19   0.980196  0.988083 -1.196398
137 -1.020204 -0.731153  1.094061
355 -1.020204  2.134241 -1.049573
349 -1.020204  0.032952 -0.256722
..        ...       ...       ...
344 -1.020204  0.892570  1.035331
235 -1.020204  0.797057  0.271845
252  0.980196  0.988083  1.886912
21   0.980196  0.892570 -0.609101
313  0.980196  1.083596  2.092466
160 -1.020204 -0.540127  0.888507
276 -1.020204  0.032952  0.036926
191  0.980196 -1.781797 -1.284492
293 -1.020204 -0.062561  0.213115
343  0.980196  0.892570 -0.550371
257 -1.020204  0.223978 -0.374182
308 -1.020204 -0.158074  1.622629
149 -1.020204 -1.686284  0.125021
130 -1.020204 -0.635640 -0.344817
151 -1.020204  0.319491 -0.726560
359 -1.020204  0.415005 -0.462276
99   0.980196 -0.922179 -0.961479
372  0.980196  0.128465  0.095656
87   0.980196 -0.922179  0.448034
330 -1.020204  0.032952 -0.550371
214 -1.020204  0.892570 -0.785290
121 -1.020204 -0.062561  0.066291
399  0.980196  1.083596 -0.990844
20  -1.020204  0.701544 -1.401952
188 -1.020204 -0.253587  0.066291
71   0.980196 -1.304232 -1.255127
106  0.980196 -1.113206 -1.020209
270  0.980196  0.510518  1.857547
348 -1.020204  0.128465  0.213115
102  0.980196 -0.540127  0.477399

[320 rows x 3 columns]

In [122]:
X_train0 = X_train.iloc[:,0].to_numpy()

In [123]:
X_train0

array([ 0.98019606, -1.02020406,  0.98019606,  0.98019606,  0.98019606,
       -1.02020406, -1.02020406, -1.02020406, -1.02020406, -1.02020406,
       -1.02020406,  0.98019606, -1.02020406,  0.98019606, -1.02020406,
        0.98019606, -1.02020406, -1.02020406,  0.98019606, -1.02020406,
        0.98019606,  0.98019606, -1.02020406, -1.02020406,  0.98019606,
        0.98019606,  0.98019606, -1.02020406, -1.02020406, -1.02020406,
       -1.02020406, -1.02020406, -1.02020406,  0.98019606,  0.98019606,
       -1.02020406,  0.98019606,  0.98019606, -1.02020406, -1.02020406,
       -1.02020406,  0.98019606, -1.02020406,  0.98019606, -1.02020406,
        0.98019606, -1.02020406, -1.02020406,  0.98019606,  0.98019606,
       -1.02020406,  0.98019606,  0.98019606, -1.02020406, -1.02020406,
       -1.02020406,  0.98019606,  0.98019606,  0.98019606,  0.98019606,
        0.98019606, -1.02020406, -1.02020406,  0.98019606,  0.98019606,
       -1.02020406,  0.98019606,  0.98019606,  0.98019606,  0.98

In [124]:
X_train1 = X_train.iloc[:, 1].to_numpy()

In [125]:
X_train1

array([-1.01769239,  0.79705706,  0.12846516,  0.60603081,  1.84770149,
       -0.54012675,  0.31949142,  0.98808332, -1.11320552, -1.49525804,
        1.08359645, -0.15807423,  0.22397829,  0.31949142, -1.11320552,
        0.12846516,  2.03872775,  0.41500455,  1.46564897, -0.34910049,
        1.84770149,  0.12846516,  0.89257019, -1.30423178, -0.15807423,
       -0.54012675,  0.98808332, -0.73115301,  2.13424088,  0.03295203,
       -0.44461362,  0.12846516,  1.65667523,  1.08359645,  0.51051768,
       -1.01769239, -1.11320552, -0.0625611 ,  0.41500455, -0.25358736,
       -0.82666613,  0.03295203,  0.70154394,  1.5611621 ,  0.79705706,
       -1.39974491, -0.0625611 ,  0.41500455, -0.25358736,  1.27462271,
        0.12846516, -1.30423178,  1.94321462, -1.20871865,  0.31949142,
       -0.92217926,  0.41500455,  0.41500455,  0.79705706,  0.89257019,
       -0.44461362, -1.78179743,  1.08359645, -0.63563988, -0.73115301,
        0.98808332, -0.54012675, -0.0625611 , -1.87731056,  0.41

In [126]:
X_train2 = X_train.iloc[:, 2].to_numpy()
X_train2

array([-0.37418169, -1.22576253,  1.88691227, -0.9027491 , -1.28449224,
        1.47580428, -0.52100597,  0.12502088,  0.47739916,  0.33057487,
        0.47739916, -0.46227625, -0.31545197,  0.30121002, -1.5781408 ,
        0.27184516,  1.76945285, -0.16862769,  2.15119598,  1.24088543,
        1.53453399,  0.03692631, -1.3138571 , -1.49004624, -0.57973568,
        2.35674998, -1.19639767,  1.09406114, -1.04957339, -0.25672226,
       -1.13766796,  0.03692631, -0.9027491 , -0.9027491 ,  1.24088543,
       -1.46068138, -1.54877595,  0.68295315, -0.46227625, -0.25672226,
        0.15438573,  0.30121002, -1.28449224,  1.123426  , -1.37258681,
       -1.22576253,  0.15438573, -0.13926283,  0.03692631,  2.23929055,
        0.77104772,  0.56549373,  0.74168287, -1.40195167, -0.31545197,
        0.56549373,  0.30121002,  1.123426  ,  0.77104772,  1.27025028,
       -1.22576253, -1.3138571 ,  0.56549373, -1.60750566,  0.27184516,
        2.09246627,  1.38770971,  0.03692631,  0.47739916,  0.27

In [127]:
import math

In [128]:
b0 = 0
b1=0
b2=0
b3=0
a = 0.001
y_train = y_train.to_numpy()

In [134]:
for i in range(0,10000):
        ypred = b0 + b1*X_train0 + b2*X_train1 + b3*X_train2
        y_pred  = 1/(1+np.exp(-ypred))
        D_b0 = -2 * sum((y_train - y_pred) * y_pred * (1 - y_pred)) 
        D_b1 = -2 * sum(X_train0 * (y_train - y_pred) * y_pred * (1 - y_pred)) 
        D_b2 = -2 * sum(X_train1 * (y_train - y_pred) * y_pred * (1 - y_pred)) 
        D_b3 = -2 * sum(X_train2 * (y_train - y_pred) * y_pred * (1 - y_pred)) 
        b0 = b0 - a * D_b0
        b1 = b1 - a * D_b1
        b2 = b2 - a * D_b2
        b3 = b3 - a * D_b3

In [135]:
print(b0,b1,b2)

-1.085813120251532 -0.13923344064766638 2.946115952240435


In [136]:
from sklearn.metrics import accuracy_score

In [137]:
X_test0 = X_test[0]

In [138]:
X_test0

209    0.980196
280    0.980196
33     0.980196
210    0.980196
93     0.980196
84     0.980196
329    0.980196
94     0.980196
266   -1.020204
126   -1.020204
9      0.980196
361    0.980196
56     0.980196
72     0.980196
132   -1.020204
42    -1.020204
278    0.980196
376    0.980196
231   -1.020204
385   -1.020204
77     0.980196
15    -1.020204
391   -1.020204
271    0.980196
0     -1.020204
396   -1.020204
114   -1.020204
225   -1.020204
262    0.980196
104    0.980196
         ...   
46    -1.020204
321    0.980196
338    0.980196
70    -1.020204
374    0.980196
39     0.980196
223   -1.020204
172    0.980196
30    -1.020204
152   -1.020204
124    0.980196
294    0.980196
255    0.980196
78     0.980196
101   -1.020204
31     0.980196
352    0.980196
268    0.980196
394    0.980196
73     0.980196
320    0.980196
140   -1.020204
5     -1.020204
45    -1.020204
388   -1.020204
246    0.980196
227   -1.020204
369    0.980196
176    0.980196
289    0.980196
Name: 0, Length: 80, dty

In [139]:
X_test1 = X_test[1]
X_test1

209    0.797057
280    2.038728
33    -0.922179
210    0.988083
93    -0.826666
84    -0.731153
329    0.892570
94    -0.826666
266    0.223978
126    0.415005
9     -0.253587
361    1.465649
56    -1.399745
72    -1.686284
132   -0.731153
42    -0.253587
278    1.370136
376    0.797057
231    0.128465
385    1.752188
77    -1.495258
15    -0.826666
391    0.892570
271    2.038728
0     -1.781797
396    1.274623
114    0.415005
225   -0.062561
262    1.656675
104   -1.781797
         ...   
46    -1.208719
321    1.465649
338    0.032952
70    -1.208719
374   -0.062561
39    -1.017692
223    2.134241
172   -1.113206
30    -0.635640
152   -0.635640
124    0.319491
294   -0.253587
255    1.370136
78    -0.922179
101   -0.922179
31    -1.017692
352    0.415005
268    0.892570
394    0.128465
73    -0.444614
320    1.370136
140   -1.781797
5     -1.017692
45    -1.399745
388    0.892570
246   -0.253587
227    1.752188
369    1.561162
176   -0.253587
289   -0.062561
Name: 1, Length: 80, dty

In [140]:
X_test2 = X_test[2]
X_test2

209   -1.401952
280    0.536129
33    -0.755925
210    0.771048
93    -1.225763
84    -0.227357
329    1.094061
94     0.389305
266    0.154386
126   -0.139263
9     -0.139263
361   -1.049573
56    -0.638465
72    -1.372587
132    0.506764
42     1.123426
278   -0.932114
376    0.125021
231   -0.814655
385   -0.286087
77    -1.255127
15     0.301210
391   -1.372587
271    0.183751
0     -1.490046
396   -1.372587
114    0.301210
225   -0.491641
262    1.622629
104   -1.431317
         ...   
46     0.271845
321    0.359940
338   -0.432911
70     0.301210
374    0.301210
39    -1.137668
223    0.947237
172    1.417075
30     0.125021
152    0.183751
124   -0.550371
294   -0.374182
255    0.594859
78     0.506764
101   -0.315452
31     1.975007
352    0.594859
268    2.180561
394   -0.315452
73     1.270250
320    2.004372
140    0.448034
5     -0.344817
45    -1.460681
388   -1.049573
246   -0.579736
227    1.857547
369   -1.284492
176   -0.667830
289    0.242480
Name: 2, Length: 80, dty

In [141]:
ypred1 = b0 + b1*X_test0 + b2*X_test1 + b3*X_train2[j]
pred1  = 1/(1+np.exp(-ypred1))
np.round(pred1)

209    1.0
280    1.0
33     0.0
210    1.0
93     0.0
84     0.0
329    1.0
94     0.0
266    1.0
126    1.0
9      0.0
361    1.0
56     0.0
72     0.0
132    0.0
42     0.0
278    1.0
376    1.0
231    1.0
385    1.0
77     0.0
15     0.0
391    1.0
271    1.0
0      0.0
396    1.0
114    1.0
225    0.0
262    1.0
104    0.0
      ... 
46     0.0
321    1.0
338    0.0
70     0.0
374    0.0
39     0.0
223    1.0
172    0.0
30     0.0
152    0.0
124    1.0
294    0.0
255    1.0
78     0.0
101    0.0
31     0.0
352    1.0
268    1.0
394    0.0
73     0.0
320    1.0
140    0.0
5      0.0
45     0.0
388    1.0
246    0.0
227    1.0
369    1.0
176    0.0
289    0.0
Length: 80, dtype: float64

In [142]:
accuracy_score(y_test,np.round(pred1))

0.875

In [76]:
for i in range
print(y_test,np.round(pred1))

83    1
53    0
70    0
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    1
30    1
73    1
33    1
90    1
4     1
76    1
77    1
12    1
31    1
Name: 2, dtype: int64 83    0.0
53    0.0
70    0.0
45    0.0
44    0.0
39    0.0
22    0.0
80    1.0
10    1.0
0     0.0
18    1.0
30    1.0
73    1.0
33    0.0
90    1.0
4     1.0
76    1.0
77    0.0
12    1.0
31    1.0
dtype: float64
